[workspace]
members = ["crates/haecceity"]

[package]
name = "quiddity"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
haecceity = { path = "crates/haecceity" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151", features = ["float_roundtrip"] }
