[workspace]
members = ["crates/haecceity"]

[package]
name = "quiddity"
version = "0.1.0-alpha.1"
edition = "2024"
license = "AGPL-3.0-only"

[dependencies]
flate2 = "1.1.10"
haecceity = { path = "crates/haecceity" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151", features = ["float_roundtrip"] }
sha2 = "0.11.0"
