//! The AP242 EXPRESS schema as data: entity and type declarations, Part 21 instance and
//! document validation, and the *family* of every entity type.
//!
//! The tables in `express_table.rs` are generated by `tools/express_table.py` from the AP242
//! MIM long forms (stepcode's copies; source URL and sha256 in each [`Edition`]):
//!
//! - [`AP242_ED4`], WG12 N11521: **AP242 edition 4** (ISO 10303-242:2025), `FILE_SCHEMA`
//!   `{ 1 0 10303 442 7 1 4 }`. Its 2407 entity types are exactly the AP242 edition 4 list of
//!   NIST's STEP File Analyzer (`sfa-data.tcl`, `ap242e4`), which also identifies edition 4 by
//!   version 7 of the object identifier (`sfa-gen.tcl`); 274 of them are not in its edition 3
//!   list (e.g. the `a3m_data_quality_*` entities). Its header says 2,404 entities; the file
//!   declares 2407.
//! - [`AP242_ED1`], WG12 N8324 (2014): **AP242 edition 1**, `{ 1 0 10303 442 1 1 4 }`, whose
//!   1726 entity types equal the analyzer's edition 1 list.
//!
//! No long form of edition 2 (`{… 442 3 1 4}`, 2020) or edition 3 (`{… 442 4 1 4}`, 2022) was
//! found (stepcode's history holds only these two; SC4's module repositories publish short
//! forms only), so files of those editions have no table of their own: they are checked as
//! an upgrade to the target.
//!
//! The writer targets exactly [`TARGET_SCHEMA`], edition 4.
//!
//! [`Edition::validate`] checks one Part 21 record: declared and instantiable entity names; the
//! attribute count; INTEGER, REAL, NUMBER, STRING, BOOLEAN, LOGICAL and BINARY kinds;
//! enumeration values; `$` only where OPTIONAL and `*` only where an inherited attribute is
//! redeclared as derived; aggregates with their bounds and element types; reference targets
//! whose types satisfy the attribute's entity or SELECT type; SELECT values of defined types
//! written as typed parameters (an untyped `0.075` as `measure_with_unit.value_component` is a
//! violation); complex instances with parts in alphabetical order, every supertype present,
//! each part's own attributes, a combination the SUPERTYPE expressions allow, and the internal
//! mapping when the set is the supertype closure of one entity type. WHERE and UNIQUE rules are
//! not evaluated; [`Edition::rules`] names them for citation. Not checked either: UNIQUE
//! aggregate elements, STRING and BINARY widths, and aggregate bounds that are expressions.

use std::collections::{BTreeSet, HashMap, HashSet};

use step_io::parser::{Attribute as Param, Graph, RawEntity};

#[rustfmt::skip]
#[path = "express_table.rs"]
mod table;

pub use table::{AP242_ED1, AP242_ED4};

/// The `FILE_SCHEMA` of the edition the writer targets: AP242 edition 4.
pub const TARGET_SCHEMA: &str =
    "AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF { 1 0 10303 442 7 1 4 }";

/// The edition the writer targets ([`TARGET_SCHEMA`]).
pub static TARGET: &Edition = &AP242_ED4;

/// Every edition with a table, oldest first.
pub static EDITIONS: [&Edition; 2] = [&AP242_ED1, &AP242_ED4];

/// One edition's schema.
#[derive(Debug)]
pub struct Edition {
    /// The `FILE_SCHEMA` identifier of the edition.
    pub file_schema: &'static str,
    pub source_url: &'static str,
    pub source_sha256: &'static str,
    /// Sorted by name.
    pub types: &'static [TypeDecl],
    /// Sorted by name.
    pub entities: &'static [EntityDecl],
}

/// A TYPE declaration (names lower case, as all names in the table).
#[derive(Debug)]
pub struct TypeDecl {
    pub name: &'static str,
    pub def: TypeDef,
    /// Labels of its WHERE rules.
    pub rules: &'static [&'static str],
}

#[derive(Debug)]
pub enum TypeDef {
    /// Member type names, sorted.
    Select(&'static [&'static str]),
    Enumeration(&'static [&'static str]),
    Defined(Ty),
}

/// An attribute or element type.
#[derive(Debug, Clone, Copy)]
pub enum Ty {
    Integer,
    Real,
    Number,
    String,
    Boolean,
    Logical,
    Binary,
    /// An entity or a defined type.
    Named(&'static str),
    Aggregate(&'static Aggregate),
}

#[derive(Debug)]
pub struct Aggregate {
    pub kind: AggregateKind,
    /// `None` when the bound is not a literal (an expression); not checked then.
    pub lower: Option<u32>,
    /// `None` for `?` or a bound that is not a literal.
    pub upper: Option<u32>,
    /// `ARRAY … OF OPTIONAL`: elements may be `$`.
    pub optional: bool,
    pub unique: bool,
    pub of: Ty,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AggregateKind {
    List,
    Set,
    Bag,
    Array,
}

/// An ENTITY declaration.
#[derive(Debug)]
pub struct EntityDecl {
    pub name: &'static str,
    pub is_abstract: bool,
    /// SUBTYPE OF, in declared order.
    pub supertypes: &'static [&'static str],
    /// SUPERTYPE OF.
    pub supertype_of: Option<Sx>,
    /// Its own explicit attributes, in declared order.
    pub attributes: &'static [Attribute],
    /// Inherited attributes it redeclares (`SELF\e.a`), by the entity that declares them.
    pub redeclared: &'static [Redeclared],
    /// Labels of its UNIQUE and WHERE rules, in declared order.
    pub rules: &'static [&'static str],
}

/// A supertype expression.
#[derive(Debug)]
pub enum Sx {
    Entity(&'static str),
    OneOf(&'static [Sx]),
    AndOr(&'static [Sx]),
    And(&'static [Sx]),
}

#[derive(Debug)]
pub struct Attribute {
    pub name: &'static str,
    pub optional: bool,
    pub ty: Ty,
}

/// An inherited explicit attribute redeclared in a subtype: with a narrower type, or (`derived`)
/// as a derived attribute, written `*` in Part 21.
#[derive(Debug)]
pub struct Redeclared {
    /// The entity declaring the attribute.
    pub entity: &'static str,
    pub attribute: &'static str,
    pub derived: bool,
    pub optional: bool,
    pub ty: Ty,
}

/// An explicit attribute as an instance writes it: its declaration and the redeclarations that
/// apply to the instance's type.
#[derive(Debug, Clone)]
pub struct Slot {
    /// The entity declaring it.
    pub entity: &'static str,
    pub name: &'static str,
    /// OPTIONAL in its declaration and in every redeclaration that applies.
    pub optional: bool,
    /// Redeclared as derived: written `*`.
    pub derived: bool,
    pub ty: Ty,
    /// The types of explicit redeclarations that apply; a value satisfies each.
    pub redeclared: Vec<Ty>,
}

/// The family of an entity type: what a PMI edit does with an instance of it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Family {
    SemanticPmi,
    Presentation,
    ValidationProperty,
    Other,
}

impl Family {
    pub fn as_str(self) -> &'static str {
        match self {
            Family::SemanticPmi => "semantic-pmi",
            Family::Presentation => "presentation",
            Family::ValidationProperty => "validation-property",
            Family::Other => "other",
        }
    }
}

/// The family rules, in order: an entity type takes the family of the first root it is (a
/// subtype of); otherwise [`Family::Other`]. Order matters where roots nest:
/// `draughting_model_item_association` is an `item_identified_representation_usage`, and
/// `annotation_occurrence` a `styled_item`.
///
/// - Semantic PMI: shape aspects (datums, datum features and targets, datum systems and their
///   compartments and elements, tolerance zones, groups) and their relationships (dimensional
///   locations, datum establishment and target features, derivation); dimensional sizes and
///   their representation; geometric tolerances and their relationships and classifications;
///   zones, plus/minus tolerances, tolerance values, limits and fits, default tolerance tables;
///   datum references and modifiers with values; threads and knurls (not other
///   `feature_definition`s); the usages binding shape aspects to faces
///   (`item_identified_representation_usage`, PMI practice §5.1); the value qualifiers of
///   §5.2.2 and §5.4 (`type_qualifier`, `value_format_type_qualifier`,
///   `measure_qualification`); user defined attributes (`general_property` and its association,
///   UDA practice §5; that a `general_property` is a UDA is stated by its name
///   'user defined attribute').
/// - Presentation: draughting model item associations, callouts and their relationships,
///   annotation occurrences (tessellated ones too) and annotation placeholder leader lines with
///   their points (`apll_point`, `apll_point_with_surface`), styled items, draughting models, saved
///   views (`model_geometric_view`, cameras, view volumes), presentation representations
///   (`mechanical_design_geometric_presentation_representation` too), sets,
///   layers and style assignments, styles, colours and pre-defined items, invisibility,
///   `mechanical_design_and_draughting_relationship`.
/// - Validation properties: no entity type. The CAx-IF validation properties are
///   `property_definition`s (with `property_definition_representation`s and ordinary
///   representations) told apart only by the name of the property definition
///   ([`VALIDATION_PROPERTY_NAMES`]); [`Edition::instance_family`] classifies by that name.
pub const FAMILY_RULES: &[(&str, Family)] = &[
    // Presentation roots that are subtypes of semantic roots or of each other come first.
    ("draughting_model_item_association", Family::Presentation),
    ("draughting_callout", Family::Presentation),
    ("draughting_callout_relationship", Family::Presentation),
    ("annotation_occurrence", Family::Presentation),
    ("annotation_placeholder_leader_line", Family::Presentation),
    ("apll_point", Family::Presentation),
    ("apll_point_with_surface", Family::Presentation),
    ("styled_item", Family::Presentation),
    ("draughting_model", Family::Presentation),
    ("model_geometric_view", Family::Presentation),
    ("camera_model", Family::Presentation),
    ("camera_usage", Family::Presentation),
    ("view_volume", Family::Presentation),
    ("presentation_representation", Family::Presentation),
    (
        "mechanical_design_geometric_presentation_representation",
        Family::Presentation,
    ),
    ("presentation_set", Family::Presentation),
    ("presentation_layer_assignment", Family::Presentation),
    ("presentation_style_assignment", Family::Presentation),
    ("presented_item", Family::Presentation),
    ("presented_item_representation", Family::Presentation),
    ("invisibility", Family::Presentation),
    (
        "mechanical_design_and_draughting_relationship",
        Family::Presentation,
    ),
    ("colour", Family::Presentation),
    ("pre_defined_item", Family::Presentation),
    ("curve_style", Family::Presentation),
    ("curve_style_font", Family::Presentation),
    ("fill_area_style", Family::Presentation),
    ("fill_area_style_colour", Family::Presentation),
    ("point_style", Family::Presentation),
    ("surface_style_usage", Family::Presentation),
    ("surface_side_style", Family::Presentation),
    ("surface_style_boundary", Family::Presentation),
    ("surface_style_fill_area", Family::Presentation),
    ("surface_style_parameter_line", Family::Presentation),
    ("surface_style_rendering", Family::Presentation),
    ("surface_style_transparent", Family::Presentation),
    ("text_style", Family::Presentation),
    // Semantic PMI.
    ("shape_aspect", Family::SemanticPmi),
    ("shape_aspect_relationship", Family::SemanticPmi),
    ("dimensional_size", Family::SemanticPmi),
    (
        "dimensional_characteristic_representation",
        Family::SemanticPmi,
    ),
    ("shape_dimension_representation", Family::SemanticPmi),
    ("geometric_tolerance", Family::SemanticPmi),
    ("geometric_tolerance_relationship", Family::SemanticPmi),
    (
        "geometric_tolerance_auxiliary_classification",
        Family::SemanticPmi,
    ),
    ("tolerance_zone_definition", Family::SemanticPmi),
    ("tolerance_zone_form", Family::SemanticPmi),
    ("runout_zone_orientation", Family::SemanticPmi),
    ("plus_minus_tolerance", Family::SemanticPmi),
    ("tolerance_value", Family::SemanticPmi),
    ("limits_and_fits", Family::SemanticPmi),
    ("default_tolerance_table", Family::SemanticPmi),
    ("default_tolerance_table_cell", Family::SemanticPmi),
    ("datum_reference", Family::SemanticPmi),
    ("datum_reference_modifier_with_value", Family::SemanticPmi),
    ("thread", Family::SemanticPmi),
    ("turned_knurl", Family::SemanticPmi),
    ("item_identified_representation_usage", Family::SemanticPmi),
    ("type_qualifier", Family::SemanticPmi),
    ("value_format_type_qualifier", Family::SemanticPmi),
    ("measure_qualification", Family::SemanticPmi),
    ("general_property", Family::SemanticPmi),
    ("general_property_association", Family::SemanticPmi),
];

/// The names of `property_definition`s that are CAx-IF validation properties (PMI practice
/// §10, UDA practice, and the geometric, assembly and tessellated validation property
/// practices).
pub const VALIDATION_PROPERTY_NAMES: &[&str] = &[
    "assembly validation property",
    "attribute validation property",
    "geometric validation property",
    "pmi validation property",
    "tessellated validation property",
];

/// What is wrong with an instance.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Kind {
    /// The name is not an entity type of the edition.
    Undeclared,
    /// The set of types is not instantiable: an ABSTRACT supertype without a subtype, a
    /// combination of subtypes the SUPERTYPE expressions exclude, or unrelated parts.
    Combination,
    /// A complex instance whose type is the supertype closure of one entity: Part 21 requires
    /// the internal mapping (a simple record).
    InternalMapping,
    /// Complex parts not in alphabetical order, or repeated.
    PartOrder,
    /// A complex instance missing the part of a supertype.
    MissingPart,
    AttributeCount,
    /// `$` for an attribute that is not OPTIONAL (or in an aggregate not of OPTIONAL elements).
    Unset,
    /// `*` where the attribute is not redeclared as derived, or a value where it is.
    Derived,
    /// A value of the wrong kind (a string for a REAL, a list for a reference, …).
    ValueType,
    Enumeration,
    /// An aggregate with too few or too many elements.
    Bound,
    /// A literal where a SELECT of defined types requires a typed parameter.
    Untyped,
    /// A typed parameter where the type is not a SELECT, or whose type is not one of its
    /// members.
    Typed,
    /// A reference whose target is not of the required entity type.
    Reference,
    /// A reference to an instance that does not exist.
    Dangling,
}

impl Kind {
    pub fn as_str(self) -> &'static str {
        match self {
            Kind::Undeclared => "undeclared",
            Kind::Combination => "combination",
            Kind::InternalMapping => "internal-mapping",
            Kind::PartOrder => "part-order",
            Kind::MissingPart => "missing-part",
            Kind::AttributeCount => "attribute-count",
            Kind::Unset => "unset",
            Kind::Derived => "derived",
            Kind::ValueType => "value-type",
            Kind::Enumeration => "enumeration",
            Kind::Bound => "bound",
            Kind::Untyped => "untyped",
            Kind::Typed => "typed",
            Kind::Reference => "reference",
            Kind::Dangling => "dangling",
        }
    }
}

/// One violation of the schema by one instance.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct Violation {
    pub id: u64,
    /// The instance's type: its entity name, or `(a b c)` for a complex instance, lower case.
    pub entity: String,
    pub kind: Kind,
    /// `entity.attribute` of the attribute concerned, if any.
    pub attribute: Option<String>,
    pub detail: String,
}

impl std::fmt::Display for Violation {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "#{} {} {}", self.id, self.entity, self.kind.as_str())?;
        if let Some(a) = &self.attribute {
            write!(f, " {a}")?;
        }
        write!(f, ": {}", self.detail)
    }
}

/// The table for a `FILE_SCHEMA` identifier: the schema name and the version of the object
/// identifier must be the edition's (`{ 1 0 10303 442 7 1 4 }` is edition 4). `None` for any
/// other schema or edition. In particular `{ 1 0 10303 442 5 1 4 }`, which NIST's STEP File
/// Analyzer also reads as edition 4 (`sfa-step.tcl`) although it says edition 4 is identified
/// by version 7 (`sfa-gen.tcl`), is not taken as edition 4 here: such a file is checked as an
/// upgrade to the target, like editions 2 and 3.
pub fn edition(file_schema: &str) -> Option<&'static Edition> {
    let id = object_id(file_schema)?;
    EDITIONS
        .iter()
        .copied()
        .find(|e| object_id(e.file_schema).as_ref() == Some(&id))
}

/// The schema name (upper case) and the object identifier's numbers.
fn object_id(s: &str) -> Option<(String, Vec<u64>)> {
    let (name, rest) = s.split_once('{')?;
    let (ids, tail) = rest.split_once('}')?;
    if !tail.trim().is_empty() {
        return None;
    }
    let ids = ids
        .split_whitespace()
        .map(|t| t.parse().ok())
        .collect::<Option<Vec<u64>>>()?;
    Some((name.trim().to_ascii_uppercase(), ids))
}

/// [`Edition::is_declared`] of the target edition.
pub fn is_declared(name: &str) -> bool {
    TARGET.is_declared(name)
}

/// [`Edition::is_a`] of the target edition.
pub fn is_a(name: &str, ancestor: &str) -> bool {
    TARGET.is_a(name, ancestor)
}

/// [`Edition::explicit_attributes`] of the target edition.
pub fn explicit_attributes(name: &str) -> Option<Vec<Slot>> {
    TARGET.explicit_attributes(name)
}

/// [`Edition::rules`] of the target edition.
pub fn rules(name: &str) -> impl Iterator<Item = &'static str> {
    TARGET.rules(name)
}

/// [`Edition::family`] of the target edition.
pub fn family(name: &str) -> Option<Family> {
    TARGET.family(name)
}

/// [`Edition::validate`] against the target edition.
pub fn validate(
    record: &RawEntity,
    target_types: &dyn Fn(u64) -> Option<Vec<String>>,
) -> Vec<Violation> {
    TARGET.validate(record, target_types)
}

/// [`Edition::validate_document`] against the target edition.
pub fn validate_document(graph: &Graph) -> Vec<Violation> {
    TARGET.validate_document(graph)
}

impl Edition {
    /// The entity declaration of `name` (any case).
    pub fn entity(&self, name: &str) -> Option<&'static EntityDecl> {
        let name = name.to_ascii_lowercase();
        let entities: &'static [EntityDecl] = self.entities;
        entities
            .binary_search_by(|e| e.name.cmp(name.as_str()))
            .ok()
            .map(|i| &entities[i])
    }

    /// The type declaration of `name` (any case).
    pub fn type_decl(&self, name: &str) -> Option<&'static TypeDecl> {
        let name = name.to_ascii_lowercase();
        let types: &'static [TypeDecl] = self.types;
        types
            .binary_search_by(|t| t.name.cmp(name.as_str()))
            .ok()
            .map(|i| &types[i])
    }

    /// Whether `name` is an entity type of the edition.
    pub fn is_declared(&self, name: &str) -> bool {
        self.entity(name).is_some()
    }

    /// Whether entity type `name` is `ancestor` or one of its subtypes.
    pub fn is_a(&self, name: &str, ancestor: &str) -> bool {
        let ancestor = ancestor.to_ascii_lowercase();
        self.entity(name)
            .is_some_and(|e| self.closure_of(e).contains(ancestor.as_str()))
    }

    /// `e` and all its supertypes.
    fn closure_of(&self, e: &'static EntityDecl) -> BTreeSet<&'static str> {
        let mut out = BTreeSet::new();
        let mut stack = vec![e];
        while let Some(e) = stack.pop() {
            if out.insert(e.name) {
                stack.extend(e.supertypes.iter().filter_map(|s| self.entity(s)));
            }
        }
        out
    }

    /// The explicit attributes of a simple instance of `name`, in Part 21 order: each
    /// supertype's (in SUBTYPE OF order, recursively, each once) before the entity's own, with
    /// the redeclarations of the entity and its supertypes applied.
    pub fn explicit_attributes(&self, name: &str) -> Option<Vec<Slot>> {
        let e = self.entity(name)?;
        let set = self.closure_of(e);
        let mut seen = HashSet::new();
        let mut out = Vec::new();
        self.collect_attributes(e, &set, &mut seen, &mut out);
        Some(out)
    }

    fn collect_attributes(
        &self,
        e: &'static EntityDecl,
        set: &BTreeSet<&'static str>,
        seen: &mut HashSet<&'static str>,
        out: &mut Vec<Slot>,
    ) {
        if !seen.insert(e.name) {
            return;
        }
        for s in e.supertypes {
            if let Some(s) = self.entity(s) {
                self.collect_attributes(s, set, seen, out);
            }
        }
        out.extend(self.own_slots(e, set));
    }

    /// `e`'s own explicit attributes with the redeclarations of the entities in `set` applied.
    fn own_slots(&self, e: &'static EntityDecl, set: &BTreeSet<&'static str>) -> Vec<Slot> {
        e.attributes
            .iter()
            .map(|a| {
                let mut slot = Slot {
                    entity: e.name,
                    name: a.name,
                    optional: a.optional,
                    derived: false,
                    ty: a.ty,
                    redeclared: Vec::new(),
                };
                for s in set.iter().filter_map(|s| self.entity(s)) {
                    for r in s.redeclared {
                        if r.entity == e.name && r.attribute == a.name {
                            if r.derived {
                                slot.derived = true;
                            } else {
                                slot.optional &= r.optional;
                                slot.redeclared.push(r.ty);
                            }
                        }
                    }
                }
                slot
            })
            .collect()
    }

    /// The labels of `name`'s own UNIQUE and WHERE rules (`UR1`, `WR1`, …), for citation.
    pub fn rules(&self, name: &str) -> impl Iterator<Item = &'static str> + use<> {
        self.entity(name)
            .map(|e| e.rules)
            .unwrap_or(&[])
            .iter()
            .copied()
    }

    /// The family of entity type `name` by [`FAMILY_RULES`]; `None` when it is not declared.
    pub fn family(&self, name: &str) -> Option<Family> {
        let e = self.entity(name)?;
        let set = self.closure_of(e);
        Some(
            FAMILY_RULES
                .iter()
                .find(|(root, _)| set.contains(root))
                .map_or(Family::Other, |&(_, f)| f),
        )
    }

    /// The family of an instance: [`Family::ValidationProperty`] for a `property_definition`
    /// whose name (its first attribute) is one of [`VALIDATION_PROPERTY_NAMES`], otherwise its
    /// type's [`family`](Self::family).
    pub fn instance_family(&self, name: &str, name_attribute: Option<&str>) -> Option<Family> {
        let family = self.family(name)?;
        if self.is_a(name, "property_definition")
            && name_attribute.is_some_and(|n| VALIDATION_PROPERTY_NAMES.contains(&n))
        {
            return Some(Family::ValidationProperty);
        }
        Some(family)
    }

    /// The violations of one record. `target_types(id)` gives the entity names of instance
    /// `#id` (one for a simple instance, the parts of a complex one), `None` when there is no
    /// such instance, and an empty list when its type is unknown (an external reference; not
    /// checked).
    pub fn validate(
        &self,
        record: &RawEntity,
        target_types: &dyn Fn(u64) -> Option<Vec<String>>,
    ) -> Vec<Violation> {
        Checker::new(self, target_types).record(record)
    }

    /// The violations of every DATA instance of a parsed file, in id order.
    pub fn validate_document(&self, graph: &Graph) -> Vec<Violation> {
        let types: HashMap<u64, Vec<String>> = graph
            .entities
            .iter()
            .map(|(&id, e)| (id, record_names(e)))
            .collect();
        let lookup = |id: u64| {
            types
                .get(&id)
                .cloned()
                .or_else(|| graph.external_references.contains_key(&id).then(Vec::new))
        };
        let mut checker = Checker::new(self, &lookup);
        graph
            .entities
            .values()
            .flat_map(|e| checker.record(e))
            .collect()
    }
}

/// The entity names of a record, upper case as written.
fn record_names(e: &RawEntity) -> Vec<String> {
    match e {
        RawEntity::Simple { name, .. } => vec![name.clone()],
        RawEntity::Complex { parts, .. } => parts.iter().map(|p| p.name.clone()).collect(),
    }
}

/// The names of the entities a supertype expression mentions.
fn sx_names(sx: &Sx, out: &mut BTreeSet<&'static str>) {
    match sx {
        Sx::Entity(n) => {
            out.insert(n);
        }
        Sx::OneOf(ops) | Sx::AndOr(ops) | Sx::And(ops) => {
            ops.iter().for_each(|op| sx_names(op, out))
        }
    }
}

/// Whether the non-empty set `d` of subtypes is a combination `sx` produces (ISO 10303-11
/// Annex B): a name alone; one operand of ONEOF; any non-empty selection of ANDOR operands;
/// every operand of AND. A name an expression mentions twice may come from either operand.
fn produces(sx: &Sx, d: &BTreeSet<&'static str>) -> bool {
    match sx {
        Sx::Entity(n) => d.len() == 1 && d.contains(n),
        Sx::OneOf(ops) => ops.iter().any(|op| {
            let mut names = BTreeSet::new();
            sx_names(op, &mut names);
            d.is_subset(&names) && produces(op, d)
        }),
        Sx::AndOr(ops) => cover(ops, d, &BTreeSet::new(), false),
        Sx::And(ops) => cover(ops, d, &BTreeSet::new(), true),
    }
}

/// Whether the operands, each contributing a combination it produces (or nothing, unless
/// `all`), can together produce exactly `d`.
fn cover(
    ops: &[Sx],
    d: &BTreeSet<&'static str>,
    covered: &BTreeSet<&'static str>,
    all: bool,
) -> bool {
    let Some((op, rest)) = ops.split_first() else {
        return covered == d;
    };
    let mut names = BTreeSet::new();
    sx_names(op, &mut names);
    let mut others = covered.clone();
    for o in rest {
        sx_names(o, &mut others);
    }
    // Present names only this operand can contribute must be in its combination; only the
    // names another operand could also contribute are a choice (none in the AP242 tables).
    let (shared, forced): (Vec<&'static str>, Vec<&'static str>) = d
        .intersection(&names)
        .copied()
        .partition(|n| others.contains(n));
    let shared_subsets = 1u128.checked_shl(shared.len() as u32).unwrap_or(u128::MAX);
    (0..shared_subsets).any(|mask| {
        let c: BTreeSet<&'static str> = shared
            .iter()
            .enumerate()
            .filter(|(i, _)| mask & (1 << i) != 0)
            .map(|(_, n)| *n)
            .chain(forced.iter().copied())
            .collect();
        if c.is_empty() {
            !all && cover(rest, d, covered, all)
        } else {
            produces(op, &c) && cover(rest, d, &covered.union(&c).copied().collect(), all)
        }
    })
}

/// A problem found in one attribute value, before it is placed on its instance.
struct Problem {
    kind: Kind,
    detail: String,
}

struct Checker<'a> {
    ed: &'a Edition,
    target_types: &'a dyn Fn(u64) -> Option<Vec<String>>,
    /// Supertype closures of target type lists (joined names), `None` when a name is undeclared.
    closures: HashMap<String, Option<BTreeSet<&'static str>>>,
    /// Per SELECT: its entity members and its defined-type members, through nested SELECTs.
    selects: HashMap<&'static str, (BTreeSet<&'static str>, BTreeSet<&'static str>)>,
}

impl<'a> Checker<'a> {
    fn new(ed: &'a Edition, target_types: &'a dyn Fn(u64) -> Option<Vec<String>>) -> Self {
        Checker {
            ed,
            target_types,
            closures: HashMap::new(),
            selects: HashMap::new(),
        }
    }

    fn record(&mut self, record: &RawEntity) -> Vec<Violation> {
        let id = record.id();
        let (entity, problems) = match record {
            RawEntity::Simple {
                name, attributes, ..
            } => {
                let entity = name.to_ascii_lowercase();
                (entity, self.simple(name, attributes))
            }
            RawEntity::Complex { parts, .. } => {
                let names: Vec<String> =
                    parts.iter().map(|p| p.name.to_ascii_lowercase()).collect();
                (format!("({})", names.join(" ")), self.complex(record))
            }
        };
        problems
            .into_iter()
            .map(|(attribute, p)| Violation {
                id,
                entity: entity.clone(),
                kind: p.kind,
                attribute,
                detail: p.detail,
            })
            .collect()
    }

    fn simple(&mut self, name: &str, values: &[Param]) -> Vec<(Option<String>, Problem)> {
        let Some(e) = self.ed.entity(name) else {
            return vec![(None, self.undeclared(name))];
        };
        let set = self.ed.closure_of(e);
        let mut out: Vec<(Option<String>, Problem)> = self
            .combination(&set)
            .into_iter()
            .map(|p| (None, p))
            .collect();
        let mut slots = Vec::new();
        self.ed
            .collect_attributes(e, &set, &mut HashSet::new(), &mut slots);
        out.extend(self.attributes(&slots, values));
        out
    }

    fn complex(&mut self, record: &RawEntity) -> Vec<(Option<String>, Problem)> {
        let RawEntity::Complex { parts, .. } = record else {
            unreachable!()
        };
        let mut out = Vec::new();
        let mut decls = Vec::new();
        for p in parts {
            match self.ed.entity(&p.name) {
                Some(e) => decls.push(e),
                None => out.push((None, self.undeclared(&p.name))),
            }
        }
        if !out.is_empty() {
            return out;
        }
        let problem = |kind, detail| (None, Problem { kind, detail });
        let written: Vec<&str> = parts.iter().map(|p| p.name.as_str()).collect();
        if written.windows(2).any(|w| w[0] >= w[1]) {
            out.push(problem(
                Kind::PartOrder,
                format!(
                    "parts {} are not in alphabetical order without repeats (ISO 10303-21 \
                     external mapping)",
                    written.join(" ")
                ),
            ));
        }
        let set: BTreeSet<&'static str> = decls.iter().map(|e| e.name).collect();
        let closure: BTreeSet<&'static str> =
            decls.iter().flat_map(|e| self.ed.closure_of(e)).collect();
        let missing: Vec<&str> = closure.difference(&set).copied().collect();
        if !missing.is_empty() {
            out.push(problem(
                Kind::MissingPart,
                format!("no part for supertype(s) {}", missing.join(" ")),
            ));
        }
        let leaves: Vec<&str> = closure
            .iter()
            .copied()
            .filter(|n| {
                !closure
                    .iter()
                    .any(|m| self.ed.entity(m).is_some_and(|m| m.supertypes.contains(n)))
            })
            .collect();
        if let [leaf] = leaves[..] {
            out.push(problem(
                Kind::InternalMapping,
                format!("the parts are the supertype closure of {leaf}: write it as a simple {leaf} record"),
            ));
        }
        out.extend(self.combination(&closure).into_iter().map(|p| (None, p)));
        for (part, e) in parts.iter().zip(&decls) {
            let slots = self.ed.own_slots(e, &closure);
            out.extend(self.attributes(&slots, &part.attributes));
        }
        out
    }

    fn undeclared(&self, name: &str) -> Problem {
        let what = if self.ed.type_decl(name).is_some() {
            "a TYPE, not an entity type"
        } else {
            "not declared"
        };
        Problem {
            kind: Kind::Undeclared,
            detail: format!(
                "{} is {what} in {}",
                name.to_ascii_lowercase(),
                self.ed.file_schema
            ),
        }
    }

    /// Whether a supertype-closed set of entity types is instantiable.
    fn combination(&self, set: &BTreeSet<&'static str>) -> Vec<Problem> {
        let mut out = Vec::new();
        let problem = |detail| Problem {
            kind: Kind::Combination,
            detail,
        };
        for &n in set {
            let Some(e) = self.ed.entity(n) else { continue };
            let subs: BTreeSet<&'static str> = set
                .iter()
                .copied()
                .filter(|s| self.ed.entity(s).is_some_and(|s| s.supertypes.contains(&n)))
                .collect();
            if subs.is_empty() {
                if e.is_abstract {
                    out.push(problem(format!(
                        "{n} is ABSTRACT and none of its subtypes is present"
                    )));
                }
                continue;
            }
            let Some(sx) = &e.supertype_of else { continue };
            let mut mentioned = BTreeSet::new();
            sx_names(sx, &mut mentioned);
            let constrained: BTreeSet<&'static str> =
                subs.intersection(&mentioned).copied().collect();
            if !constrained.is_empty() && !produces(sx, &constrained) {
                out.push(problem(format!(
                    "SUPERTYPE OF of {n} does not allow its subtypes {} together",
                    constrained.iter().copied().collect::<Vec<_>>().join(" ")
                )));
            }
        }
        // Parts that share no supertype are not one instance.
        let mut component: BTreeSet<&'static str> = set.iter().take(1).copied().collect();
        loop {
            let grown: BTreeSet<&'static str> = set
                .iter()
                .copied()
                .filter(|n| {
                    component.contains(n)
                        || self.ed.entity(n).is_some_and(|e| {
                            e.supertypes.iter().any(|s| component.contains(s))
                                || component.iter().any(|c| {
                                    self.ed.entity(c).is_some_and(|c| c.supertypes.contains(n))
                                })
                        })
                })
                .collect();
            if grown.len() == component.len() {
                break;
            }
            component = grown;
        }
        if component.len() != set.len() {
            let rest: Vec<&str> = set.difference(&component).copied().collect();
            out.push(problem(format!(
                "{} share no supertype with {}",
                rest.join(" "),
                component.iter().copied().collect::<Vec<_>>().join(" ")
            )));
        }
        out
    }

    fn attributes(&mut self, slots: &[Slot], values: &[Param]) -> Vec<(Option<String>, Problem)> {
        if slots.len() != values.len() {
            let names: Vec<String> = slots
                .iter()
                .map(|s| format!("{}.{}", s.entity, s.name))
                .collect();
            return vec![(
                None,
                Problem {
                    kind: Kind::AttributeCount,
                    detail: format!(
                        "{} attributes, the schema has {} ({})",
                        values.len(),
                        slots.len(),
                        names.join(", ")
                    ),
                },
            )];
        }
        let mut out = Vec::new();
        for (slot, value) in slots.iter().zip(values) {
            let mut problems = Vec::new();
            match value {
                Param::Unset if slot.derived => problems.push(Problem {
                    kind: Kind::Derived,
                    detail: "`$` for an attribute redeclared as derived: `*` expected".into(),
                }),
                Param::Unset if !slot.optional => problems.push(Problem {
                    kind: Kind::Unset,
                    detail: "`$` for an attribute that is not OPTIONAL".into(),
                }),
                Param::Unset => {}
                Param::Derived if !slot.derived => problems.push(Problem {
                    kind: Kind::Derived,
                    detail: "`*` for an attribute that is not redeclared as derived".into(),
                }),
                Param::Derived => {}
                _ if slot.derived => problems.push(Problem {
                    kind: Kind::Derived,
                    detail: "a value for an attribute redeclared as derived: `*` expected".into(),
                }),
                _ => {
                    self.value(value, slot.ty, "", &mut problems);
                    for &ty in &slot.redeclared {
                        self.narrowed(value, slot.ty, ty, &mut problems);
                    }
                }
            }
            let mut seen = HashSet::new();
            out.extend(
                problems
                    .into_iter()
                    .filter(|p| seen.insert(p.detail.clone()))
                    .map(|p| (Some(format!("{}.{}", slot.entity, slot.name)), p)),
            );
        }
        out
    }

    /// Check `v` against `ty`, a redeclaration narrowing the declared type `base`. The Part 21
    /// encoding is the declaration's: a value of a defined type in a `base` SELECT is a typed
    /// parameter even when `ty` is that defined type (ISO 10303-21 writes the attribute as its
    /// declared type), so the typed parameter's type must be `ty` or a type defined from it.
    fn narrowed(&mut self, v: &Param, base: Ty, ty: Ty, out: &mut Vec<Problem>) {
        let Param::Typed { type_name, value } = v else {
            return self.value(v, ty, "", out);
        };
        if self.select_of(base).is_none()
            || self.select_of(ty).is_some()
            || matches!(ty, Ty::Named(n) if self.ed.entity(n).is_some())
        {
            return self.value(v, ty, "", out);
        }
        let Ty::Named(narrow) = ty else {
            return self.value(value, ty, "", out);
        };
        let mut t = type_name.to_ascii_lowercase();
        loop {
            if t == narrow {
                return;
            }
            match self.ed.type_decl(&t).map(|d| &d.def) {
                Some(TypeDef::Defined(Ty::Named(u))) => t = u.to_string(),
                _ => break,
            }
        }
        push(
            out,
            "",
            Kind::Typed,
            format!("{type_name}(…) is not {narrow}, the attribute's redeclared type"),
        );
    }

    /// The SELECT a type is, through defined types that rename one (`TYPE a = b;` with `b` a
    /// SELECT); `None` when it is not a SELECT.
    fn select_of(&self, ty: Ty) -> Option<&'static str> {
        let Ty::Named(mut n) = ty else { return None };
        loop {
            match self.ed.type_decl(n).map(|t| &t.def) {
                Some(TypeDef::Select(_)) => return Some(n),
                Some(TypeDef::Defined(Ty::Named(u))) => n = u,
                _ => return None,
            }
        }
    }

    /// Check `v` against `ty`; `at` locates it within the attribute (`[2][0]`).
    fn value(&mut self, v: &Param, ty: Ty, at: &str, out: &mut Vec<Problem>) {
        match (v, ty) {
            (Param::Unset, _) => push(out, at, Kind::Unset, "`$` inside a value".into()),
            (Param::Derived, _) => push(out, at, Kind::Derived, "`*` inside a value".into()),
            (Param::Typed { .. }, Ty::Named(_)) if self.select_of(ty).is_some() => {
                let select = self.select_of(ty).expect("checked");
                self.select(v, select, at, out);
            }
            (Param::Typed { type_name, .. }, _) => push(
                out,
                at,
                Kind::Typed,
                format!("typed parameter {type_name}(…) where the type is not a SELECT"),
            ),
            (Param::Integer(_), Ty::Integer | Ty::Number)
            | (Param::Real(_), Ty::Real | Ty::Number)
            | (Param::String(_), Ty::String)
            | (Param::Binary(_), Ty::Binary) => {}
            (Param::Enum(e), Ty::Boolean)
                if ["T", "F"].iter().any(|b| e.eq_ignore_ascii_case(b)) => {}
            (Param::Enum(e), Ty::Logical)
                if ["T", "F", "U"].iter().any(|b| e.eq_ignore_ascii_case(b)) => {}
            (Param::List(items), Ty::Aggregate(a)) => {
                let n = items.len() as u32;
                let (lo, hi) = match a.kind {
                    AggregateKind::Array => {
                        let len = a.lower.zip(a.upper).map(|(l, h)| h + 1 - l);
                        (len, len)
                    }
                    _ => (a.lower, a.upper),
                };
                if lo.is_some_and(|lo| n < lo) || hi.is_some_and(|hi| n > hi) {
                    push(
                        out,
                        at,
                        Kind::Bound,
                        format!(
                            "{n} elements, the {:?} allows [{}:{}]",
                            a.kind,
                            lo.map_or("?".into(), |l| l.to_string()),
                            hi.map_or("?".into(), |h| h.to_string())
                        ),
                    );
                }
                for (i, item) in items.iter().enumerate() {
                    let at = format!("{at}[{i}]");
                    if matches!(item, Param::Unset) && a.optional {
                        continue;
                    }
                    self.value(item, a.of, &at, out);
                }
            }
            (_, Ty::Named(n)) => {
                if self.ed.entity(n).is_some() {
                    self.reference(v, n, at, out);
                } else {
                    match self.ed.type_decl(n).map(|t| &t.def) {
                        Some(TypeDef::Select(_)) => self.select(v, n, at, out),
                        Some(TypeDef::Enumeration(values)) => match v {
                            Param::Enum(e) if values.contains(&e.to_ascii_lowercase().as_str()) => {
                            }
                            Param::Enum(e) => push(
                                out,
                                at,
                                Kind::Enumeration,
                                format!(".{e}. is not a value of {n} ({})", values.join(", ")),
                            ),
                            _ => push(
                                out,
                                at,
                                Kind::ValueType,
                                format!("{} for enumeration {n}", describe(v)),
                            ),
                        },
                        Some(TypeDef::Defined(inner)) => self.value(v, *inner, at, out),
                        None => push(
                            out,
                            at,
                            Kind::Undeclared,
                            format!("type {n} is not declared"),
                        ),
                    }
                }
            }
            (_, ty) => push(
                out,
                at,
                Kind::ValueType,
                format!("{} for {}", describe(v), ty_name(ty)),
            ),
        }
    }

    fn reference(&mut self, v: &Param, entity: &str, at: &str, out: &mut Vec<Problem>) {
        let Param::EntityRef(id) = v else {
            push(
                out,
                at,
                Kind::ValueType,
                format!("{} for entity {entity}", describe(v)),
            );
            return;
        };
        match self.target(*id) {
            Target::Missing => push(out, at, Kind::Dangling, format!("#{id} does not exist")),
            Target::Unknown => {}
            Target::Undeclared(names) => push(
                out,
                at,
                Kind::Reference,
                format!("#{id} is {names}, not declared; {entity} expected"),
            ),
            Target::Types(names, set) => {
                if !set.contains(entity) {
                    push(
                        out,
                        at,
                        Kind::Reference,
                        format!("#{id} is {names}, not {entity}"),
                    );
                }
            }
        }
    }

    fn select(&mut self, v: &Param, select: &'static str, at: &str, out: &mut Vec<Problem>) {
        let (entities, defined) = self.select_members(select);
        match v {
            Param::EntityRef(id) => match self.target(*id) {
                Target::Missing => push(out, at, Kind::Dangling, format!("#{id} does not exist")),
                Target::Unknown => {}
                Target::Undeclared(names) => push(
                    out,
                    at,
                    Kind::Reference,
                    format!("#{id} is {names}, not declared; a member of SELECT {select} expected"),
                ),
                Target::Types(names, set) => {
                    if set.is_disjoint(&entities) {
                        push(
                            out,
                            at,
                            Kind::Reference,
                            format!("#{id} is {names}, not an entity type of SELECT {select}"),
                        );
                    }
                }
            },
            Param::Typed { type_name, value } => {
                let t = type_name.to_ascii_lowercase();
                match defined.iter().find(|d| **d == t) {
                    Some(&d) => self.value(value, Ty::Named(d), at, out),
                    None => push(
                        out,
                        at,
                        Kind::Typed,
                        format!("{type_name} is not a defined type of SELECT {select}"),
                    ),
                }
            }
            _ if defined.is_empty() => push(
                out,
                at,
                Kind::ValueType,
                format!("{} for SELECT {select} of entity types", describe(v)),
            ),
            _ => push(
                out,
                at,
                Kind::Untyped,
                format!(
                    "untyped {} for SELECT {select}: a typed parameter (one of {}) is required",
                    describe(v),
                    defined.iter().copied().collect::<Vec<_>>().join(", ")
                ),
            ),
        }
    }

    /// The entity members and the defined-type members of a SELECT, through nested SELECTs.
    fn select_members(
        &mut self,
        select: &'static str,
    ) -> (BTreeSet<&'static str>, BTreeSet<&'static str>) {
        if let Some(m) = self.selects.get(select) {
            return m.clone();
        }
        let (mut entities, mut defined) = (BTreeSet::new(), BTreeSet::new());
        let mut seen = HashSet::new();
        let mut stack = vec![select];
        while let Some(s) = stack.pop() {
            if !seen.insert(s) {
                continue;
            }
            let Some(TypeDef::Select(members)) = self.ed.type_decl(s).map(|t| &t.def) else {
                continue;
            };
            for &m in *members {
                if self.ed.entity(m).is_some() {
                    entities.insert(m);
                } else if let Some(s) = self.select_of(Ty::Named(m)) {
                    // A SELECT, or a defined type renaming one: its members are this SELECT's
                    // (ISO 10303-21 types only values of defined types that are not SELECTs).
                    stack.push(s);
                } else {
                    defined.insert(m);
                }
            }
        }
        self.selects
            .insert(select, (entities.clone(), defined.clone()));
        (entities, defined)
    }

    fn target(&mut self, id: u64) -> Target {
        let Some(names) = (self.target_types)(id) else {
            return Target::Missing;
        };
        if names.is_empty() {
            return Target::Unknown;
        }
        let key = names.join(" ").to_ascii_lowercase();
        let ed = self.ed;
        let set = self
            .closures
            .entry(key.clone())
            .or_insert_with(|| {
                let mut set = BTreeSet::new();
                for n in &names {
                    set.extend(ed.closure_of(ed.entity(n)?));
                }
                Some(set)
            })
            .clone();
        match set {
            Some(set) => Target::Types(key, set),
            None => Target::Undeclared(key),
        }
    }
}

fn push(out: &mut Vec<Problem>, at: &str, kind: Kind, detail: String) {
    let detail = if at.is_empty() {
        detail
    } else {
        format!("{at}: {detail}")
    };
    out.push(Problem { kind, detail });
}

enum Target {
    Missing,
    Unknown,
    Undeclared(String),
    Types(String, BTreeSet<&'static str>),
}

fn describe(v: &Param) -> String {
    match v {
        Param::Integer(i) => format!("INTEGER {i}"),
        Param::Real(r) => format!("REAL {r:?}"),
        Param::String(_) => "a STRING".into(),
        Param::Enum(e) => format!(".{e}."),
        Param::Binary(_) => "a BINARY".into(),
        Param::EntityRef(id) => format!("#{id}"),
        Param::Unset => "`$`".into(),
        Param::Derived => "`*`".into(),
        Param::List(items) => format!("a list of {}", items.len()),
        Param::Typed { type_name, .. } => format!("{type_name}(…)"),
    }
}

fn ty_name(ty: Ty) -> String {
    match ty {
        Ty::Integer => "INTEGER".into(),
        Ty::Real => "REAL".into(),
        Ty::Number => "NUMBER".into(),
        Ty::String => "STRING".into(),
        Ty::Boolean => "BOOLEAN".into(),
        Ty::Logical => "LOGICAL".into(),
        Ty::Binary => "BINARY".into(),
        Ty::Named(n) => n.into(),
        Ty::Aggregate(a) => format!("{:?} OF {}", a.kind, ty_name(a.of)).to_ascii_uppercase(),
    }
}
